name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    name: PHPUnit Tests
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php: [ '8.0' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: nanasess/setup-php@master
        with:
          php-version: "${{ matrix.php }}"
      - name: Install dependencies
        run: composer --prefer-source --no-progress --ansi install
      - name: Run tests
        run: ./vendor/bin/phpunit -v tests
